### ISSUE TITLE
Does this library help to embed FB page plugins?

### ISSUE THREAD

**Issue by rodneyjoyce** [zyramedia/ng2-facebook-sdk#30]
Hello,

Does this library help to embed FB page plugins?
https://developers.facebook.com/docs/plugins/page-plugin

**Comment by ihadeed** [comment]
@rodneyjoyce no it doesn't. I just had a quick look at the link. It seems like they just require you to add an HTML markup. I don't see why an Angular 2 service/component is needed here.

**Comment by rodneyjoyce** [comment]
@ihadeed : I tried to embed the HTML but it does not render. In Angular1 I was using a NPM library that rendered it correctly. I had the same issue with the AddThis widget.

**Comment by ihadeed** [comment]
@rodneyjoyce can you send me a link of the library so I can have a look at what they did and try to replicate it for Angular 2?

**Comment by rodneyjoyce** [comment]
Ok, so the library that I was using for ng1 and Facebook was this one:  https://github.com/pc035860/angular-easyfb

**Comment by ihadeed** [comment]
Sorry for the long delay @rodneyjoyce 

I'm currently working on v2 of this module. The work is being done in the `v2` branch in this repo. 

So far I added `fb-page`, `fb-like` and `fb-follow` components. I will add the rest of them soon. 

You can see examples in the [ng2-facebook-sdk-example repo](https://github.com/zyramedia/ng2-facebook-sdk-example). Or try it yourself:

Install with `@next` tag.
```
npm i --save ng2-facebook-sdk@next
```

Remove `FacebookService` and add `FacebookModule` in your `NgModule`
```typescript
import { FacebookModule } from 'ng2-facebook-sdk';
@NgModule({
  imports: [FacebookModule]
})
```

All previous code should work the same way. The only change is that the interfaces no longer have the `Facebook` prefix, and the `Ui` prefix is now `UI`.

To try out the components, do the following:
```
<fb-like href="path/to/site/or/page"></fb-like>
<fb-follow ...></fb-follow>
<fb-page ...></fb-page>
```

The components accept all attributes documented on the Facebook SDK site here: https://developers.facebook.com/docs/plugins
There are two differences in the names: 
- all attribute names use camel caps instead of dashes, example `show-faces` is `showFaces`
- all attribute name do not have `data-` prefix


I would love to hear some feedback. Any issues, suggestions, questions .. etc

Thanks!

**Comment by ihadeed** [comment]
Closing this issue, opened a discussion/progress tracker here: https://github.com/zyramedia/ng2-facebook-sdk/issues/53
